services:
  db:
    image: postgres:16-bookworm
    ports:
      - "5432:5432"   # optional, nur wenn du vom Host drauf willst
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cory
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cory

volumes:
  postgres_data:

networks:
  cory:
    external: true
    name: cory
